project_id = "amwqwtnplsxppmstxjkb"

[functions.dtdc-create-consignment]
verify_jwt = false

[functions.dtdc-shipping-label]
verify_jwt = false

[functions.dtdc-track]
verify_jwt = false

[functions.dtdc-cancel]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false